package com.neoproc.financialagent.worker;

import com.neoproc.financialagent.common.credentials.PortalCredentials;
import com.neoproc.financialagent.common.crypto.EnvelopeCipher;
import com.neoproc.financialagent.common.match.EmployeeMatcher;
import com.neoproc.financialagent.contract.payroll.EnvelopeStatus;
import com.neoproc.financialagent.contract.payroll.PayrollSubmitRequest;
import com.neoproc.financialagent.contract.payroll.RosterDiff;
import com.neoproc.financialagent.contract.payroll.SubmitRequestBody;
import com.neoproc.financialagent.contract.payroll.SubmitResultBody;
import com.neoproc.financialagent.worker.envelope.EnvelopeIo;
import com.neoproc.financialagent.worker.portal.PortalDescriptor;
import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.options.LoadState;
import com.microsoft.playwright.options.WaitForSelectorState;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Submit adapter for CCSS Sicere — the per-client salary save flow.
 *
 * <p>The portal is unusual along three axes; the adapter encapsulates all
 * three so the descriptor stays tiny and the framework stays generic:
 * <ol>
 *   <li><b>Two-variation entry.</b> If the planilla has not been
 *       "presented" yet, the navigation goes through {@code Presentar}
 *       → period text → {@code Continuar}. If it has been presented
 *       already, the navigation goes through the Lista de Facturas
 *       table → radio button on the {@code PRESENTADA} row →
 *       {@code Modificar}. The adapter detects which state the post-login
 *       page is in and picks the right path.</li>
 *   <li><b>Per-row Aplicar.</b> The portal silently drops pending edits
 *       if multiple {@code Nuevo Salario} fields are dirty when
 *       Aplicar Salarios fires. The adapter therefore loops:
 *       fill one row → Tab → click Aplicar → wait → next row. Cost: N
 *       round-trips per planilla; the descriptor's rate-limit budgets
 *       for it.</li>
 *   <li><b>Two distinct totals.</b> The header shows
 *       {@code Total Salario} (working/draft) and
 *       {@code Total de Salarios Reportados} (saved). The latter is the
 *       gating signal — {@code grandTotal == portalReported} on the
 *       result envelope. {@code Total Salario} is exposed as a
 *       diagnostic only.</li>
 * </ol>
 *
 * <p>Status routing follows PraxisIntegrationHandoff.md §15.4:
 * {@code SUCCESS} only when the roster diff is empty AND
 * {@code portalReported == expected}; {@code PARTIAL} when the roster
 * diff is non-empty (regardless of totals); {@code MISMATCH} when the
 * roster diff is empty but totals diverge; {@code FAILED} on hard
 * errors with {@code errorDetail.category} from §15.5.
 */
final class CcssSicereSubmitAdapter extends AbstractSubmitAdapter {

    private static final Logger log = LoggerFactory.getLogger(CcssSicereSubmitAdapter.class);

    // Stable PrimeFaces ids (from the operator's recordings). The
    // <table>:<rowIndex>:<componentId>_input pattern is generated by
    // PrimeFaces and survives template tweaks; the <table> id itself
    // would only churn on a major form rename.
    private static final String SALARY_INPUT_SUFFIX = "txtNuevoSalario_input";
    private static final String PAGINATOR_BOTTOM = "[id='formAPL:planillaCambiosTable_paginator_bottom']";
    // PrimeFaces buttons compose icon + text via two child spans; the
    // button's accessible name includes the icon's text content, making
    // role=button[name='…'] selectors unreliable across locales and icon
    // sets. button:has-text(…) matches the <button> whose visible
    // descendant text contains the label — what the operator sees and
    // what stays stable across PrimeFaces template tweaks.
    // :visible filters out hidden dialog/modal buttons that share the same
    // visible text — strict-mode locator violations otherwise. The CCSS
    // page renders several PrimeFaces dialogs (e.g. frmDlgExpPass) that
    // sit in the DOM even when not displayed; scoping to visible-only
    // disambiguates without needing to know each dialog's id.
    private static final String APLICAR_SALARIOS = "button:visible:has-text(\"Aplicar Salarios\")";
    private static final String LOGOUT_LINK = "a:visible:has-text(\"exit_to_app\")";
    private static final String LOGOUT_CONFIRM = "button:visible:has-text(\"Sí\")";

    // Post-login navigation. The post-login app lives at /autogestion/...
    // on the same host as the /afiliacion/ login page; the Lista de
    // Facturas URL is stable and links the PRESENTADA row whose
    // {@code Modificar} button drives Variation B.
    private static final String LISTA_FACTURAS_URL =
            "https://aissfa.ccss.sa.cr/autogestion/factura/listado/index.xhtml";

    /**
     * Buttons the adapter will refuse to click, ever — visible-text denylist
     * enforced by {@link #safeClick}. The adapter's happy path does not
     * select any of these by selector, but a future refactor that
     * accidentally introduced a click whose locator resolved to one of
     * these labels would fail fast rather than commit the action.
     *
     * <p>Why these are forbidden:
     * <ul>
     *   <li>{@code Facturar Planilla} formally bills/submits the planilla.
     *       Once clicked, the planilla is legally submitted to CCSS and the
     *       worker becomes responsible for that submission — well outside
     *       the save-only contract from §15.6. The HITL final-submit user
     *       task owns this action; the agent never does.</li>
     * </ul>
     */
    private static final List<String> FORBIDDEN_BUTTON_LABELS = List.of(
            "facturar planilla",
            "facturar"
    );

    // Header total cells — the portal labels these "Total Salario:" and
    // "Total de Salarios Reportados:" with the value in a sibling cell.
    // Selectors verified against the Lista de Trabajadores page (April
    // 2026 screenshot); update if PrimeFaces upgrades change the markup.
    private static final String TOTAL_SALARIO_VALUE =
            "xpath=//*[contains(normalize-space(.), 'Total Salario:')][not(contains(normalize-space(.), 'Reportados'))]/following-sibling::*[1]";
    private static final String TOTAL_SALARIO_REPORTADO_VALUE =
            "xpath=//*[contains(normalize-space(.), 'Total de Salarios Reportados:')]/following-sibling::*[1]";

    // Captured during beforeSteps, consumed in buildSubmitOutcome.
    private BigDecimal canonicalGrandTotal = BigDecimal.ZERO;
    private BigDecimal portalCurrentTotal = BigDecimal.ZERO;
    private BigDecimal portalReportedTotal = BigDecimal.ZERO;
    private RosterDiff rosterDiff = new RosterDiff(List.of(), List.of());
    private List<SubmitResultBody.SubmittedRow> submittedRows = List.of();
    // Name-drift signals captured during the match loop: cédula matched
    // uniquely so the salary was applied, but canonical and portal names
    // disagreed. HITL reviews these via the PARTIAL routing.
    private List<SubmitResultBody.Signal> nameDriftSignals = List.of();
    private String sourceCaptureEnvelopeId;
    private String clientIdentifier;
    // Dry-run mode: navigates, scrapes, matches, but does NOT touch the
    // portal (no fill, no Aplicar). Set with -Dparams.dryRun=true (CLI).
    // Useful for the first-contact run against a real portal — the
    // operator can verify selector accuracy + variation detection +
    // matching without committing any changes.
    private boolean dryRun;

    @Override
    public void beforeSteps(PortalDescriptor descriptor,
                            Page page,
                            Map<String, String> bindings,
                            Map<String, List<Map<String, String>>> listBindings,
                            PortalCredentials credentials,
                            RunManifest manifest) {

        clientIdentifier = bindings.get("params.clientIdentifier");
        if (clientIdentifier == null || clientIdentifier.isBlank()) {
            throw new IllegalStateException(
                    "ccss-sicere is per-client; envelope must carry task.clientIdentifier "
                            + "(corporate id, e.g. \"3101680139\")");
        }

        dryRun = Boolean.parseBoolean(bindings.getOrDefault("params.dryRun", "false"));
        log.info("ccss-sicere starting clientIdentifier={} dryRun={}", clientIdentifier, dryRun);
        if (dryRun) {
            manifest.step("dry-run",
                    "params.dryRun=true — no fill, no Aplicar Salarios click; "
                            + "navigation + scrape + match still execute");
        }

        List<Canonical> canonicals = loadCanonical(bindings);
        if (canonicals.isEmpty()) {
            throw new IllegalStateException(
                    "ccss-sicere submit requires at least one canonical employee on "
                            + "params.source.submitRequest");
        }
        canonicalGrandTotal = canonicals.stream()
                .map(Canonical::salary)
                .reduce(BigDecimal.ZERO, BigDecimal::add)
                .setScale(2, RoundingMode.HALF_UP);
        manifest.step("source",
                "canonicals=" + canonicals.size()
                        + " expectedTotal=" + canonicalGrandTotal
                        + " sourceCaptureEnvelopeId=" + sourceCaptureEnvelopeId);

        openPlanillaForEdit(page, manifest);
        log.info("ccss-sicere on planilla edit page; scraping pre-aplicar totals");

        // Pre-Aplicar snapshot — diagnostic, mostly for the manifest. The
        // post-loop scrape is what feeds the result envelope.
        portalCurrentTotal = readMoneyOrZero(page, TOTAL_SALARIO_VALUE);
        portalReportedTotal = readMoneyOrZero(page, TOTAL_SALARIO_REPORTADO_VALUE);
        log.info("pre-aplicar totals portalCurrent={} portalReported={}",
                portalCurrentTotal, portalReportedTotal);
        manifest.step("pre-aplicar-totals",
                "portalCurrent=" + portalCurrentTotal
                        + " portalReported=" + portalReportedTotal);

        List<SubmitResultBody.SubmittedRow> matchedRows = new ArrayList<>();
        List<RosterDiff.MissingFromPortal> missingFromPortal = new ArrayList<>();
        List<SubmitResultBody.Signal> drifts = new ArrayList<>();
        List<PortalRow> displayedAll = scrapeAllPages(page, manifest);
        boolean[] displayedMatched = new boolean[displayedAll.size()];

        for (Canonical c : canonicals) {
            Optional<EmployeeMatcher.MatchResult> matched = findMatchingRow(c, displayedAll);
            if (matched.isEmpty()) {
                missingFromPortal.add(new RosterDiff.MissingFromPortal(
                        c.id(), c.name(), c.salary(), c.attributes()));
                log.info("match-skip canonicalId={} (no portal row, or duplicated cédula with name mismatch)", c.id());
                manifest.step("match-skip",
                        "canonicalId=" + c.id() + " (no portal row, or duplicated cédula with name mismatch)");
                continue;
            }
            int globalIdx = matched.get().index();
            boolean nameConfirmed = matched.get().nameConfirmed();
            displayedMatched[globalIdx] = true;
            PortalRow row = displayedAll.get(globalIdx);

            if (nameConfirmed) {
                log.info("match-hit canonicalId={} -> portalIdentification={} salary={}",
                        c.id(), row.identification(), c.salary());
            } else {
                // Cédula matched uniquely on the planilla but the names
                // diverged — apply the salary (cédula is the primary key)
                // and surface a NAME_DRIFT signal so HITL can confirm it's
                // the same person before final submit.
                log.warn("match-hit-name-drift canonicalId={} canonicalName='{}' portalName='{}' (cédula unique — applying salary)",
                        c.id(), c.name(), row.name());
                manifest.step("match-hit-name-drift",
                        "canonicalId=" + c.id()
                                + " canonicalName='" + c.name() + "'"
                                + " portalName='" + row.name() + "'");
                drifts.add(new SubmitResultBody.Signal(
                        "NAME_DRIFT",
                        null, null, null,
                        row.identification(),
                        c.name(),                  // canonical name
                        row.name(),                // portal name
                        null, null));
            }

            applySalary(page, row, c.salary(), manifest);
            matchedRows.add(new SubmitResultBody.SubmittedRow(
                    row.identification(), row.name(), c.salary()));
        }

        // Anything portal-side that we never matched and that has a
        // non-zero current salary is a deregistration candidate. Rows
        // with zero current salary are ignored — those are placeholders
        // the portal already considers inactive.
        List<RosterDiff.MissingFromPayroll> missingFromPayroll = new ArrayList<>();
        for (int i = 0; i < displayedAll.size(); i++) {
            if (displayedMatched[i]) continue;
            PortalRow row = displayedAll.get(i);
            BigDecimal lastKnown = row.currentSalary();
            if (lastKnown == null || lastKnown.signum() == 0) continue;
            missingFromPayroll.add(new RosterDiff.MissingFromPayroll(
                    row.identification(), row.name(), lastKnown));
        }

        rosterDiff = new RosterDiff(missingFromPortal, missingFromPayroll);
        submittedRows = List.copyOf(matchedRows);
        nameDriftSignals = List.copyOf(drifts);
        log.info("roster-diff missingFromPortal={} missingFromPayroll={} nameDrift={} expected={}",
                missingFromPortal.size(), missingFromPayroll.size(),
                nameDriftSignals.size(), canonicalGrandTotal);
        manifest.step("roster-diff",
                "missingFromPortal=" + missingFromPortal.size()
                        + " missingFromPayroll=" + missingFromPayroll.size()
                        + " nameDrift=" + nameDriftSignals.size()
                        + " expected=" + canonicalGrandTotal);

        // Re-scrape the headline totals after the per-row Aplicar loop —
        // these feed the result envelope. The header section sits above
        // the table on every page, so we don't need to navigate back.
        portalCurrentTotal = readMoneyOrZero(page, TOTAL_SALARIO_VALUE);
        portalReportedTotal = readMoneyOrZero(page, TOTAL_SALARIO_REPORTADO_VALUE);
        log.info("post-aplicar totals portalCurrent={} portalReported={}",
                portalCurrentTotal, portalReportedTotal);
        manifest.step("post-aplicar-totals",
                "portalCurrent=" + portalCurrentTotal
                        + " portalReported=" + portalReportedTotal);
    }

    @Override
    protected SubmitOutcome buildSubmitOutcome(Map<String, String> scraped,
                                               List<Map<String, String>> scrapedRows,
                                               Map<String, String> bindings,
                                               PortalCredentials credentials,
                                               RunManifest manifest) {

        // Portfolio-wide status routing per §15.4. portalReported is the
        // gating signal; Total Salario is diagnostic. expected/portalReported
        // ride on the envelope explicitly so BPMN can branch on either.
        //
        // NAME_DRIFT signals also bump SUCCESS → PARTIAL: the salary was
        // applied (cédula matched uniquely) but a human should confirm the
        // identity before the final-submit user task fires. rosterDiff stays
        // empty so the register/dereg lifecycle subprocesses do not run.
        boolean totalsMatch = canonicalGrandTotal.compareTo(portalReportedTotal) == 0;
        String status;
        if (!rosterDiff.isEmpty() || !nameDriftSignals.isEmpty()) {
            status = EnvelopeStatus.PARTIAL;
        } else if (!totalsMatch) {
            status = EnvelopeStatus.MISMATCH;
        } else {
            status = EnvelopeStatus.SUCCESS;
        }

        manifest.step("verify",
                "status=" + status
                        + " expected=" + canonicalGrandTotal
                        + " portalReported=" + portalReportedTotal
                        + " portalCurrent=" + portalCurrentTotal
                        + " rosterDiff.empty=" + rosterDiff.isEmpty()
                        + " nameDrift=" + nameDriftSignals.size());

        SubmitResultBody.Review review = buildReview(
                status, canonicalGrandTotal, portalReportedTotal, rosterDiff, nameDriftSignals);

        SubmitResultBody body = new SubmitResultBody(
                status,
                null, // CCSS Sicere is save-only — no portal-issued submission id
                new SubmitResultBody.Totals(
                        "CRC",
                        portalReportedTotal,            // grandTotal == portalReported (legacy field)
                        submittedRows.size(),
                        canonicalGrandTotal,            // expected
                        portalReportedTotal),           // portalReported (explicit)
                submittedRows,
                rosterDiff,
                null,
                review);

        String runId = require(bindings, "runtime.runId");
        String businessKey = bindings.getOrDefault(
                "params.businessKey", "ccss-sicere::" + clientIdentifier + "::" + runId);

        return new SubmitOutcome(
                status,
                body,
                "ccss-sicere",
                businessKey,
                "agent-worker/ccss-sicere",
                sourceCaptureEnvelopeId,
                clientIdentifier);
    }

    @Override
    public void afterCapture(Page page, Map<String, String> bindings, RunManifest manifest) {
        // Best-effort logout. The session is corporate-id-bound and
        // server-side; leaking it doesn't expose data, but a clean
        // teardown is polite and frees the portal-side rate-limit slot
        // sooner. PortalRunService swallows any exception here.
        page.locator(LOGOUT_LINK).first().click();
        page.locator(LOGOUT_CONFIRM).waitFor();
        page.locator(LOGOUT_CONFIRM).click();
        page.waitForLoadState(LoadState.LOAD);
        manifest.step("logout", "exit_to_app + Sí confirmation");
    }

    // --- Variation detection + navigation -----------------------------------

    private void openPlanillaForEdit(Page page, RunManifest manifest) {
        // Try Variation B first (Lista de Facturas with PRESENTADA row).
        // The post-login menu always exposes "Factura" — clicking it reveals
        // the listing. If a row with Modificar is visible, click radio +
        // Modificar. Else fall through to Variation A (the Presentar flow).
        if (tryVariationB(page, manifest)) return;
        if (tryVariationA(page, manifest)) return;
        throw new IllegalStateException(
                "ccss-sicere: neither Variation A (Presentar) nor Variation B "
                        + "(Lista de Facturas with Modificar row) elements were "
                        + "visible after login — portal layout may have changed");
    }

    private boolean tryVariationB(Page page, RunManifest manifest) {
        // Lista de Facturas lives on a different path from the login page
        // (login at /afiliacion/, app at /autogestion/...). Navigate
        // directly rather than chasing the post-login menu — saves a click
        // and is robust to menu-label changes.
        page.navigate(LISTA_FACTURAS_URL);
        page.waitForLoadState(LoadState.LOAD);

        Locator modificar = page.locator("button:visible:has-text(\"Modificar\")").first();
        if (modificar.count() == 0) {
            manifest.step("variation-detect", "B: no Modificar button visible at " + LISTA_FACTURAS_URL);
            return false;
        }
        // Clicking the row's radio button selects it; PrimeFaces requires
        // this before Modificar fires (without it, the action raises a
        // 'select a row' validation error).
        Locator presentadaRow = page.locator(
                "tr:has(td:has-text('PRESENTADA')):has(button:has-text('Modificar'))").first();
        if (presentadaRow.count() == 0) {
            manifest.step("variation-detect", "B: Modificar visible but no PRESENTADA row");
            return false;
        }
        presentadaRow.locator(".ui-radiobutton-box").first().click();
        safeClick(modificar, "Modificar");
        page.waitForSelector(PAGINATOR_BOTTOM,
                new Page.WaitForSelectorOptions().setState(WaitForSelectorState.VISIBLE));
        manifest.step("variation-B",
                "selected PRESENTADA row, opened Modificar; on planilla edit page");
        return true;
    }

    private boolean tryVariationA(Page page, RunManifest manifest) {
        Locator presentar = page.locator("button:visible:has-text(\"Presentar\")").first();
        if (presentar.count() == 0) {
            manifest.step("variation-detect", "A: no Presentar button visible");
            return false;
        }
        safeClick(presentar, "Presentar");
        // Period selection — the recording double-clicks the period text.
        // Without a period parameter we'd need a fixture-driven disambiguation;
        // for now, double-click the first period entry visible (Lista de
        // Facturas only ever has ONE PRESENTADA-equivalent open at a time,
        // per the operator's confirmation).
        Locator periodText = page.locator(
                "text=/La planilla del período \\d{2}\\/\\d{2}/").first();
        periodText.dblclick();
        safeClick(page.locator("button:visible:has-text(\"Continuar\")"), "Continuar");
        page.waitForSelector(PAGINATOR_BOTTOM,
                new Page.WaitForSelectorOptions().setState(WaitForSelectorState.VISIBLE));
        manifest.step("variation-A",
                "Presentar -> period dblclick -> Continuar; on planilla edit page");
        return true;
    }

    // --- Pagination + per-row Aplicar ---------------------------------------

    private List<PortalRow> scrapeAllPages(Page page, RunManifest manifest) {
        // Read the total page count upfront from the paginator's
        // "Página X de Y" indicator. Defends against the silent no-op
        // when "Next Page" is rendered-but-disabled (PrimeFaces marks
        // the disabled state inconsistently across versions; counting
        // upfront is the robust signal).
        int totalPages = readTotalPages(page);
        log.info("paginator reports totalPages={}", totalPages);

        List<PortalRow> all = new ArrayList<>();
        for (int pageIdx = 1; pageIdx <= totalPages; pageIdx++) {
            List<PortalRow> pageRows = scrapeCurrentPage(page, pageIdx);
            all.addAll(pageRows);
            log.info("scraped page {}/{} rows={} runningTotal={}",
                    pageIdx, totalPages, pageRows.size(), all.size());
            manifest.step("scrape-page",
                    "page=" + pageIdx + "/" + totalPages
                            + " rows=" + pageRows.size()
                            + " runningTotal=" + all.size());
            if (pageIdx < totalPages && !gotoNextPage(page)) {
                log.warn("expected to advance to page {} but Next was no-op; stopping",
                        pageIdx + 1);
                break;
            }
        }
        // Return to page 1 — the per-row Aplicar loop walks pages by id-match
        // anyway, and the post-loop totals scrape reads from the header
        // (visible on every page) so position-after-loop doesn't matter for
        // totals; consistency matters for screenshots.
        gotoFirstPage(page);
        return all;
    }

    /**
     * Parse the paginator's "Página X de Y" text to get the total page
     * count. Robust against PrimeFaces version churn — the visible text
     * is more stable than the underlying CSS classes that mark the
     * Next-link's disabled state. Returns 1 if the text doesn't match,
     * which is the safe default for a single-page table (where the
     * paginator chrome may render but the page-of-pages text may be
     * formatted differently or absent).
     */
    private int readTotalPages(Page page) {
        try {
            String text = page.locator(PAGINATOR_BOTTOM).innerText();
            java.util.regex.Matcher m = java.util.regex.Pattern
                    .compile("Página\\s+\\d+\\s+de\\s+(\\d+)")
                    .matcher(text);
            if (m.find()) {
                return Integer.parseInt(m.group(1));
            }
            log.warn("paginator text did not match 'Página X de Y' pattern: {}",
                    text.replaceAll("\\s+", " "));
        } catch (RuntimeException e) {
            log.warn("could not read paginator text — defaulting totalPages=1", e);
        }
        return 1;
    }

    private List<PortalRow> scrapeCurrentPage(Page page, int pageIdx) {
        // Anchor on <tr> elements within the table body that contain the
        // salary input. Earlier attempt used [id^='formAPL:planillaCambiosTable:']
        // which incorrectly matched the PrimeFaces <span> wrapper around the
        // input (same id prefix, no <td> children) — so cell scraping
        // returned empty strings and matching missed everything.
        Locator rows = page.locator("tbody tr:has(input[id$='" + SALARY_INPUT_SUFFIX + "'])");
        int n = rows.count();
        List<PortalRow> out = new ArrayList<>(n);
        for (int i = 0; i < n; i++) {
            Locator row = rows.nth(i);
            String rawId = textOrEmpty(row.locator("td").nth(1));
            String identification = stripIdTypePrefix(rawId);
            String name = textOrEmpty(row.locator("td").nth(2));
            BigDecimal currentSalary = parseMoneyOrNull(textOrEmpty(row.locator("td").nth(3)));
            String inputId = row.locator("input[id$='" + SALARY_INPUT_SUFFIX + "']")
                    .first()
                    .getAttribute("id");
            if (i < 2) {
                log.info("scrape-row[{}] rawId='{}' strippedId='{}' name='{}' salario='{}' inputId='{}'",
                        i, rawId, identification, name, currentSalary, inputId);
            }
            out.add(new PortalRow(pageIdx, inputId, identification, rawId, name, currentSalary));
        }
        return out;
    }

    /**
     * CCSS Sicere displays employee IDs as {@code "<tipo>/<numero>"}
     * (e.g., {@code "0/119960589"} where {@code 0} indicates Cédula
     * Nacional). Praxis sends the bare cédula digits; strip the type
     * prefix at scrape time so {@link EmployeeMatcher#normalizeId}
     * compares apples to apples. Portal-specific normalization belongs
     * here, not in the generic matcher.
     */
    private static String stripIdTypePrefix(String raw) {
        if (raw == null) return "";
        int slash = raw.indexOf('/');
        return slash < 0 ? raw.trim() : raw.substring(slash + 1).trim();
    }

    private boolean gotoNextPage(Page page) {
        // PrimeFaces' paginator marks the next-link as disabled via
        // class on the link itself ("ui-paginator-next ui-state-disabled")
        // OR aria-disabled="true". Check both — version-to-version drift
        // shifts the marker.
        Locator next = page.locator(PAGINATOR_BOTTOM + " a.ui-paginator-next").first();
        if (next.count() == 0) {
            // Fallback: try by accessibility name. Not all paginators
            // expose a stable class.
            next = page.locator(PAGINATOR_BOTTOM + " >> role=link[name='Next Page']").first();
            if (next.count() == 0) return false;
        }
        if (isDisabled(next)) return false;
        next.click();
        page.waitForLoadState(LoadState.LOAD);
        return true;
    }

    private static boolean isDisabled(Locator locator) {
        String cls = locator.getAttribute("class");
        if (cls != null && cls.contains("ui-state-disabled")) return true;
        String aria = locator.getAttribute("aria-disabled");
        return "true".equalsIgnoreCase(aria);
    }

    private void gotoFirstPage(Page page) {
        Locator first = page.locator(PAGINATOR_BOTTOM + " a.ui-paginator-first").first();
        if (first.count() == 0) {
            first = page.locator(PAGINATOR_BOTTOM + " >> role=link[name='First Page']").first();
            if (first.count() == 0) return;
        }
        if (isDisabled(first)) return;
        first.click();
        page.waitForLoadState(LoadState.LOAD);
    }

    private void applySalary(Page page, PortalRow row, BigDecimal salary, RunManifest manifest) {
        // Navigate to the row's page first if we've drifted (the per-row
        // Aplicar can re-render and reset to page 1).
        ensureOnPage(page, row.pageIndex());

        if (dryRun) {
            // Don't even fill the input — leaves the planilla truly
            // untouched. The operator gets the matching trace + roster
            // diff + pre-state totals on the result envelope, then re-runs
            // without dryRun for the real save.
            manifest.step("aplicar-DRYRUN",
                    "id=" + row.identification() + " wouldSave=" + salary.toPlainString());
            return;
        }

        // CRITICAL: re-locate the input by the row's cédula text at apply
        // time, NOT by the stored inputId. PrimeFaces renumbers positional
        // row indexes after each Aplicar's ajax response (the row that
        // received the change can shift in the new ordering), so the
        // inputId captured at scrape time becomes stale by iteration 2+.
        // Anchor on the cédula text in a <td> within the row instead — the
        // cédula is unique on the planilla and survives reordering.
        Locator targetRow = page.locator(
                "tbody tr:has(td:has-text(\"" + row.rawIdentification() + "\"))");
        Locator input = targetRow.locator("input[id$='" + SALARY_INPUT_SUFFIX + "']").first();
        input.waitFor(new Locator.WaitForOptions()
                .setState(WaitForSelectorState.VISIBLE)
                .setTimeout(10_000));
        input.scrollIntoViewIfNeeded();
        input.click();
        input.fill(salary.toPlainString());
        input.press("Tab");
        safeClick(page.locator(APLICAR_SALARIOS), "Aplicar Salarios");
        // PrimeFaces does an ajax round-trip on Aplicar that replaces the
        // table's DOM. waitForLoadState(LOAD) doesn't wait for ajax (LOAD
        // only fires on initial navigation). A short fixed delay lets the
        // ajax response render and the new <tr>/inputs settle before the
        // next iteration's waitForSelector queries them. 800ms is well
        // above typical PrimeFaces ajax round-trips and well below any
        // sane portal-side rate-limit threshold.
        page.waitForTimeout(800);
        manifest.step("aplicar",
                "id=" + row.identification() + " salary=" + salary.toPlainString());
    }

    /**
     * Click guarded against {@link #FORBIDDEN_BUTTON_LABELS}. Reads the
     * locator's current visible text and refuses if it matches a forbidden
     * label after whitespace+case normalization. The {@code expectedLabel}
     * parameter is informational — it appears in the failure message so a
     * developer can see at a glance which call site fired.
     *
     * <p>The check is best-effort: if the locator can't be read (detached,
     * not yet visible), the click proceeds. The forbidden-button danger
     * window is when a refactor accidentally points an existing
     * {@code safeClick} at the wrong element, not when an element is
     * present-but-unreachable.
     */
    private static void safeClick(Locator locator, String expectedLabel) {
        String visible = "";
        try {
            visible = locator.first().innerText().trim();
        } catch (RuntimeException ignored) {
            // Locator may be a button-by-role that doesn't expose innerText
            // the same way; fall through to click. The denylist's value is
            // catching obvious refactor mistakes, not adversarial input.
        }
        String normalized = visible.replaceAll("\\s+", " ").trim().toLowerCase(java.util.Locale.ROOT);
        for (String forbidden : FORBIDDEN_BUTTON_LABELS) {
            if (normalized.equals(forbidden)) {
                throw new IllegalStateException(
                        "Refusing to click forbidden button: visible='" + visible
                                + "' expected='" + expectedLabel + "'. "
                                + "ccss-sicere is save-only (§15.6); Facturar Planilla "
                                + "is owned by the HITL final-submit user task, never the agent.");
            }
        }
        locator.click();
    }

    private void ensureOnPage(Page page, int targetPage) {
        // Cheap implementation: jump to first, then click Next (targetPage-1)
        // times. Adequate for ≤ a few hundred employees; real-world planillas
        // top out far below that.
        gotoFirstPage(page);
        for (int i = 1; i < targetPage; i++) {
            if (!gotoNextPage(page)) return;
        }
    }

    // --- Canonical input loading --------------------------------------------

    private List<Canonical> loadCanonical(Map<String, String> bindings) {
        String submitPath = bindings.get("params.source.submitRequest");
        if (submitPath == null || submitPath.isBlank()) return List.of();

        PayrollSubmitRequest env = EnvelopeIo.read(Path.of(submitPath), PayrollSubmitRequest.class);
        sourceCaptureEnvelopeId = env.task() != null ? env.task().sourceCaptureEnvelopeId() : null;
        SubmitRequestBody body = decodeBody(env);
        List<Canonical> out = new ArrayList<>(body.employees().size());
        for (SubmitRequestBody.SubmitEmployee e : body.employees()) {
            out.add(new Canonical(e.id(), e.displayName(), e.salary(), e.attributes()));
        }
        return out;
    }

    private static SubmitRequestBody decodeBody(PayrollSubmitRequest env) {
        if (env.encryption() == null) {
            return EnvelopeIo.MAPPER.convertValue(env.request(), SubmitRequestBody.class);
        }
        if (!(env.request() instanceof String ciphertext)) {
            throw new IllegalStateException(
                    "submit-request marked encrypted but request field is not a ciphertext string");
        }
        EnvelopeCipher cipher = EnvelopeIo.defaultCipher();
        return EnvelopeIo.decryptBody(ciphertext, env.encryption(), cipher, SubmitRequestBody.class);
    }

    // --- Helpers ------------------------------------------------------------

    private Optional<EmployeeMatcher.MatchResult> findMatchingRow(Canonical c, List<PortalRow> rows) {
        List<String> ids = new ArrayList<>(rows.size());
        List<String> names = new ArrayList<>(rows.size());
        for (PortalRow r : rows) {
            ids.add(r.identification());
            names.add(r.name());
        }
        // matchWithDrift accepts a unique-cédula match even when names
        // diverge — the caller (the match loop) emits a NAME_DRIFT signal
        // for HITL review and still applies the salary. Per-planilla
        // cédulas are unique on both sides; the strict name-confirm is
        // overcautious for typo'd display names ("EVELYN GODINES" on
        // AutoPlanilla vs "GODINEZ BOZA EVELYN NATALIA" on CCSS).
        Optional<EmployeeMatcher.MatchResult> result = c.name() != null
                ? EmployeeMatcher.matchWithDrift(c.id(), c.name(), ids, names)
                : EmployeeMatcher.matchById(c.id(), ids)
                        .map(idx -> new EmployeeMatcher.MatchResult(idx, true));
        if (result.isEmpty()) {
            // Diagnose precisely: did the ID miss entirely, or was the
            // canonical cédula duplicated on the portal side (which forces
            // matchWithDrift to fall back to strict name-confirm)?
            Optional<Integer> byIdOnly = EmployeeMatcher.matchById(c.id(), ids);
            if (byIdOnly.isEmpty()) {
                log.info("match-debug canonical-id-not-found canonicalId='{}' normalizedCanonical='{}' portalIds={}",
                        c.id(), EmployeeMatcher.normalizeId(c.id()), ids);
            } else {
                int idx = byIdOnly.get();
                log.info("match-debug duplicate-cedula-with-name-mismatch canonicalId='{}' canonicalName='{}' firstPortalName='{}'",
                        c.id(), c.name(), names.get(idx));
            }
        }
        return result;
    }

    private static String textOrEmpty(Locator loc) {
        if (loc.count() == 0) return "";
        try {
            return loc.innerText().trim();
        } catch (RuntimeException e) {
            return "";
        }
    }

    private static BigDecimal readMoneyOrZero(Page page, String selector) {
        try {
            String raw = page.locator(selector).first().innerText().trim();
            BigDecimal parsed = parseMoneyOrNull(raw);
            return parsed == null ? BigDecimal.ZERO : parsed;
        } catch (RuntimeException e) {
            log.debug("could not read totals from {} — defaulting to 0", selector, e);
            return BigDecimal.ZERO;
        }
    }

    private static BigDecimal parseMoneyOrNull(String raw) {
        if (raw == null || raw.isBlank()) return null;
        try {
            return new BigDecimal(raw.replace(",", "").trim()).setScale(2, RoundingMode.HALF_UP);
        } catch (NumberFormatException nfe) {
            return null;
        }
    }

    private static SubmitResultBody.Review buildReview(
            String status, BigDecimal canonical, BigDecimal portal, RosterDiff diff,
            List<SubmitResultBody.Signal> nameDrifts) {
        if (!EnvelopeStatus.MISMATCH.equals(status) && !EnvelopeStatus.PARTIAL.equals(status)) {
            return null;
        }
        List<SubmitResultBody.Signal> signals = new ArrayList<>();
        if (canonical.compareTo(portal) != 0) {
            signals.add(new SubmitResultBody.Signal(
                    "TOTAL_GAP", canonical, portal, portal.subtract(canonical),
                    null, null, null, null));
        }
        diff.missingFromPortal().forEach(m -> signals.add(new SubmitResultBody.Signal(
                "MISSING_FROM_PORTAL", null, null, null,
                m.id(), m.name(), m.expectedSalary(), null)));
        diff.missingFromPayroll().forEach(m -> signals.add(new SubmitResultBody.Signal(
                "MISSING_FROM_PAYROLL", null, null, null,
                m.id(), m.displayName(), null, m.lastKnownSalary())));
        signals.addAll(nameDrifts);

        StringBuilder summary = new StringBuilder();
        if (canonical.compareTo(portal) != 0) {
            BigDecimal gap = portal.subtract(canonical).abs();
            String direction = portal.compareTo(canonical) > 0
                    ? "Portal exceeds expected" : "Expected exceeds portal";
            summary.append(direction).append(" by ").append(gap.toPlainString()).append(" CRC");
        }
        if (!diff.isEmpty()) {
            if (!summary.isEmpty()) summary.append("; ");
            int mfp = diff.missingFromPortal().size();
            int mfpay = diff.missingFromPayroll().size();
            if (mfp > 0) summary.append(mfp).append(" employee(s) missing from portal");
            if (mfpay > 0) {
                if (mfp > 0) summary.append(", ");
                summary.append(mfpay).append(" missing from payroll");
            }
        }
        if (!nameDrifts.isEmpty()) {
            if (!summary.isEmpty()) summary.append("; ");
            summary.append(nameDrifts.size())
                    .append(" name disagreement(s) — cédula matched, names differ (HITL review)");
        }
        return new SubmitResultBody.Review(
                severityFor(status), summary.toString(), signals,
                List.of("FINAL_SUBMIT", "RESUBMIT", "ESCALATE"));
    }

    /**
     * Map an envelope status onto the {@code review.severity} enum the
     * schema accepts ({@code INFO|WARN|ERROR}). Reconciliation drift
     * (MISMATCH) is a hard reconciliation failure and surfaces as ERROR;
     * roster lifecycle work and name drifts (PARTIAL) are review-grade
     * and surface as WARN.
     */
    private static String severityFor(String status) {
        if (EnvelopeStatus.MISMATCH.equals(status)) return "ERROR";
        return "WARN";
    }

    /** Internal canonical employee shape, matches MockPayrollAdapter's. */
    private record Canonical(String id, String name, BigDecimal salary, Map<String, String> attributes) {
        Canonical {
            attributes = attributes == null ? Map.of() : Map.copyOf(attributes);
        }
    }

    /**
     * One row of the planilla edit table, scraped pre-Aplicar.
     *
     * <p>{@code rawIdentification} preserves the portal's display form
     * (e.g. {@code "0/119960589"}) — used at apply time to re-locate the
     * row by text content, since PrimeFaces renumbers positional row
     * indexes after each Aplicar's ajax response. {@code inputId} is
     * captured for diagnostic logging only; do not rely on it across
     * iterations.
     */
    private record PortalRow(int pageIndex,
                             String inputId,
                             String identification,
                             String rawIdentification,
                             String name,
                             BigDecimal currentSalary) {}
}
